/* =====================================================================
   coffee-data.js
   Hadchity's curated collection — 15 real, well-known coffee origins
   and styles. This is the "your own collected content" the brief wants.
   All facts are real; EDIT the notes/why fields into your own voice.
   ===================================================================== */
const COFFEES = [
  { name: "Ethiopia Yirgacheffe", origin: "Gedeo Zone, Ethiopia", roast: "Light",
    notes: "Jasmine, bergamot, lemon, and a tea-like body.",
    brew: "Pour-over (V60) or filter", process: "Washed",
    why: "The benchmark for floral, citrus-forward coffee. Ethiopia is coffee's birthplace, and Yirgacheffe is its most recognizable name." },
  { name: "Colombia Huila", origin: "Huila, Colombia", roast: "Medium",
    notes: "Caramel, red apple, balanced acidity.",
    brew: "Drip or pour-over", process: "Washed",
    why: "The dependable all-rounder. Huila's high altitude and volcanic soil produce clean, sweet, crowd-pleasing cups." },
  { name: "Sumatra Mandheling", origin: "Sumatra, Indonesia", roast: "Dark",
    notes: "Earthy, cedar, dark chocolate, low acidity.",
    brew: "French press or espresso", process: "Wet-hulled (Giling Basah)",
    why: "Heavy-bodied and savory thanks to the island's unique wet-hulling. Polarizing, but a classic for a reason." },
  { name: "Kenya AA", origin: "Central Highlands, Kenya", roast: "Light-Medium",
    notes: "Blackcurrant, tomato, bright winey acidity.",
    brew: "Pour-over", process: "Washed (double)",
    why: "AA is the top grade by bean size. Kenyan coffee's intense fruit-acid punch is unlike anything else." },
  { name: "Guatemala Antigua", origin: "Antigua Valley, Guatemala", roast: "Medium",
    notes: "Cocoa, toffee, subtle smoke, full body.",
    brew: "Drip or espresso", process: "Washed",
    why: "Grown in volcanic ash between three volcanoes. Rich and chocolatey with a hint of spice." },
  { name: "Brazil Cerrado", origin: "Minas Gerais, Brazil", roast: "Medium-Dark",
    notes: "Peanut, milk chocolate, low acidity, nutty finish.",
    brew: "Espresso base", process: "Natural",
    why: "Brazil is the world's largest producer. Cerrado's nutty sweetness is the backbone of countless espresso blends." },
  { name: "Costa Rica Tarrazú", origin: "Tarrazú, Costa Rica", roast: "Medium",
    notes: "Honey, citrus, clean and crisp.",
    brew: "Pour-over or drip", process: "Honey",
    why: "Honey-processed beans dry with some fruit mucilage left on, giving a sweet, syrupy clarity." },
  { name: "Jamaica Blue Mountain", origin: "Blue Mountains, Jamaica", roast: "Medium",
    notes: "Mild, smooth, sweet, no bitterness.",
    brew: "Drip", process: "Washed",
    why: "Among the most expensive coffees on earth. Famous for an exceptionally smooth, refined, low-bitterness cup." },
  { name: "Yemen Mocha", origin: "Bani Matar, Yemen", roast: "Medium-Dark",
    notes: "Wine, dried fruit, chocolate, wild complexity.",
    brew: "Cezve / Turkish or espresso", process: "Natural (sun-dried)",
    why: "Some of the oldest cultivated coffee in the world. Intense, funky, and historically the origin of the word 'mocha'." },
  { name: "Panama Geisha", origin: "Boquete, Panama", roast: "Light",
    notes: "Jasmine, peach, tropical fruit, floral perfume.",
    brew: "Pour-over", process: "Washed",
    why: "The variety that broke auction records. Delicate, tea-like, and astonishingly aromatic — a special-occasion coffee." },
  { name: "Honduras Marcala", origin: "La Paz, Honduras", roast: "Medium",
    notes: "Brown sugar, stone fruit, gentle acidity.",
    brew: "Drip or pour-over", process: "Washed",
    why: "An emerging origin with a protected designation. Sweet, approachable, and increasingly excellent." },
  { name: "Rwanda Nyungwe", origin: "Western Province, Rwanda", roast: "Light-Medium",
    notes: "Red berry, floral, juicy and clean.",
    brew: "Pour-over", process: "Washed",
    why: "Rwanda's Bourbon varietals produce sparkling, fruit-driven cups that have put East Africa back on the map." },
  { name: "India Monsooned Malabar", origin: "Malabar Coast, India", roast: "Dark",
    notes: "Musty-sweet, spice, very low acidity, full body.",
    brew: "Espresso or French press", process: "Monsooned",
    why: "Beans are exposed to monsoon winds for months, swelling and mellowing them into something genuinely one-of-a-kind." },
  { name: "El Salvador Pacamara", origin: "Apaneca-Ilamatepec, El Salvador", roast: "Medium",
    notes: "Green apple, caramel, herbal, big body.",
    brew: "Pour-over or espresso", process: "Washed",
    why: "Pacamara is a giant-bean hybrid developed in El Salvador. Distinctive, complex, and a roaster favorite." },
  { name: "Tanzania Peaberry", origin: "Mount Kilimanjaro, Tanzania", roast: "Medium",
    notes: "Blackberry, lemon, bright and lively.",
    brew: "Pour-over or drip", process: "Washed",
    why: "Peaberry means a single round bean per cherry instead of two — denser, and prized for a concentrated, vibrant cup." }
];
